FROM debian:jessie

ENV DEBIAN_FRONTEND noninteractive

# Debug info - can be removed
RUN du -s --exclude=proc /

RUN echo "Yes, do as I say!" | apt-get purge \
      debconf-i18n \
      iproute2 \
      ncurses-base \
      ncurses-bin \
      e2fslibs \
      libcomerr2 && \
    echo "Yes, do as I say!" | apt-get purge \
      acl \
      bash \
      inetutils-ping \
      insserv \
      libcap2-bin \
      libgpg-error0 \
      libkmod2 \
      libncurses5 \
      libncursesw5 \
      libprocps3 \
      libsemanage-common \
      libsepol1 \
      libsmartcols1 \
      libudev1 \
      libustr-1.0-1 \
      startpar \
      tzdata

RUN sed -i 's/bash/sh/g' /etc/passwd

RUN apt-get update && \
    apt-get install -y --no-install-recommends cdebconf

ENV DEBCONF_USE_CDEBCONF yes

COPY debconf_2_all.deb /

RUN cp /usr/share/debconf/confmodule /tmp

RUN dpkg -i /debconf_2_all.deb

RUN echo "exec /usr/lib/cdebconf/dpkg-preconfigure $0 \"$@"\" >/usr/sbin/dpkg-preconfigure && \
    chmod a+x /usr/sbin/dpkg-preconfigure

RUN mkdir /usr/share/debconf && \
    mv /tmp/confmodule /usr/share/debconf

RUN echo "Yes, do as I say!" | apt-get purge perl-base

COPY perl /usr/bin/

RUN cd /usr/share && \
    tar -czf copyrights.tar.gz common-licenses doc/*/copyright && \
    sed 's|doc/\*/copyright|copyrights.tar.gz|' /etc/motd && \
    rm -rf \
      /usr/share/doc/*/copyright \
      /usr/share/common-licenses

RUN apt-get clean && \
    rm -r \
      ~/.bashrc \
      /debconf_2_all.deb \
      /etc/bash_completion.d \
      /etc/systemd \
      /usr/lib/locale/C.UTF-8 \
      /usr/share/doc \
      /usr/share/info \
      /usr/share/locale \
      /usr/share/man \
      /var/cache/debconf/* \
      /var/lib/apt/lists/* \
      /var/log/*