cassandra:
  image: cassandra:2.2.4
  container_name: cassandra-test
  ports:
    - 9042

kong:
  image: hacfi/kong
  container_name: kong-test
  ports:
    - 7946:7946
    - 8000:8000
    - 8001:8001
    - 8443:8443
  links:
    - cassandra:cassandra
